### ISSUE TITLE
悬挂网站备案号

### ISSUE THREAD

**Issue by chenweiask** [kahosan/home-page#10]
请问我能修改右下角的footer吗？做网站备案的话，必须悬挂网站备案号。

**Comment by kahosan** [comment]
修改这个地方就行，这是 footer 组件右边的文字信息

https://github.com/kahosan/home-page/blob/5376538c9b56f7cf21cd1b447250e1acf47e7b02/src/components/footer/index.tsx#L27-L30

**Comment by chenweiask** [comment]
感谢回复。
如果要修改这个文件的话，是不是就必须手动部署或者自己打包docker文件了？
我尝试着把app目录映射出来，但这样docker根本跑不起来，报错说缺少文件。

**Comment by kahosan** [comment]
是的
