### ISSUE TITLE
MacOS下Safari浏览器链接处理问题

### ISSUE THREAD

**Issue by kas12323** [kahosan/home-page#14]
例如：本程序运行在192.168.1.101，我在网页中添加了一个指向为192.168.1.201的网址，点击后Safari会跳转到“http://192.168.1.101/192.168.1.201/”.

**Comment by kahosan** [comment]
路径要添加 http 或 https 前缀
比如之前为 `192.168.1.201` 改为 `http://192.168.1.201`

**Comment by kas12323** [comment]
抱歉，是我大意了，好巧不巧我就在Mac上点的那个没加http前缀的链接，没有注意到这个。在 2024年3月12日，14:15，kaho ***@***.***> 写道：﻿
路径要添加 http 或 https 前缀
比如之前为 192.168.1.201 改为 http://192.168.1.201
