### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by Sworddust** [kahosan/home-page#8]
第一个建议：可以对卡片进行分区域吗，比如Nas下的服务为一组，设置标题Nas;可以再增加一个分区，设置自定义标题，像娱乐、电影、购物，区域里可以添加卡片。这是我画的简单示例图
![screenshot-20230928-115435](https://github.com/kahosan/home-page/assets/54519184/c21f2ad7-cb1f-4e3c-a6e5-44200c0c3fcd)
第二个建议：可以拖拽卡片进行自定义排序，有时候如果添加的多了，但是想重新排序，可以进行拖拽排序这样的场景

**Comment by kahosan** [comment]
非常感谢你的建议，分组功能等有空时我会考虑一下

排序因为实现起来比较复杂，可能需要更多的时间。
可以先修改 `services.json` 这个文件里的顺序暂时解决

如果你有意愿帮助实现这个功能的话，也欢迎 PR

**Comment by kahosan** [comment]
分组功能已经可以测试了，可以请你试用 [这个分支](https://github.com/kahosan/home-page/tree/feat/group) 吗
然后，我编写这个 Home Page 本意只是有一个简单的页面能够方便我直接跳转，所以这个分支我不会合并到主线
主线会一直保持这样，但这个分支我也会持续维护。

有什么问题欢迎继续提问
